### PR TITLE
feature: added champions search

### PR DESCRIPTION
**Pull request by rcmuniz1994**
filter_champions

filtered_champions

### CODE REVIEW

**Review by gustavoFreireS — APPROVED** [review]
the way this is working right now maybe is not the best for people with low speed data (3g or 2g) to minimize this problem you can do two things:
1 - limit the search to start only after 3 letters
2 - put a loader while you are searching for champions

**Comment by zenobiopereira** [comment]
Your expected behavior is only to show the champions which starts with the typed characters?
- Giving some context, I'll be kinda lost considering that i do not remember things so well and sometimes want to search something by half name or group of characters.
It could be hard and turn the search in a useless functionality since the user will not be able to find what he really wants if not by scrolling and looking through the photos/names.

**Comment by gustavoFreireS** [comment]
> Your expected behavior is only to show the champions which starts with the typed characters?
> 
> * Giving some context, I'll be kinda lost considering that i do not remember things so well and sometimes want to search something by half name or group of characters.
>   It could be hard and turn the search in a useless functionality since the user will not be able to find what he really wants if not by scrolling and looking through the photos/names.

to solve this you can start by using the `Array.prototype.includes`

**Comment by rcmuniz1994** [comment]
> the way this is working right now maybe is not the best for people with low speed data (3g or 2g) to minimize this problem you can do two things:
> 1 - limit the search to start only after 3 letters
> 2 - put a loader while you are searching for champions

**Comment by rcmuniz1994** [comment]
@gustavoFreireS 

1- limit the search to start only after 3 letters. **R:** I'll do it right now.

2 - put a loader while you are searching for champions **R:** I'll do this on other Pull Request.

**Pull request closed without merging**
